wordpress:
    image: shaneburkhart/wordpress
    links:
        - db:mysql
    ports:
        - 80:80
    volumes:
        - /data/www:/var/www/html

db:
    image: shaneburkhart/mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
    volumes:
        - /data/mysql:/var/lib/mysql
